package com.tallerexpress.config;

import java.sql.*;

public final class Database {
  private static final String URL = "jdbc:postgresql://localhost:5433/tallerexpress";
  private static final String USER = "tallerexpress";
  private static final String PASSWORD = "tallerexpress";
  private static final String ADMIN_USERNAME = "admin";
  private static final String ADMIN_PASSWORD = "admin123";

  private Database() {}

  public static Connection getConnection() throws SQLException {
    return DriverManager.getConnection(URL, USER, PASSWORD);
  }

  public static void initialize() throws SQLException {
    String[] ddl = {
      "CREATE TABLE IF NOT EXISTS clients(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,document VARCHAR(30) UNIQUE NOT NULL,name VARCHAR(120) NOT NULL,phone VARCHAR(30),email VARCHAR(120),active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)",
      "CREATE TABLE IF NOT EXISTS vehicles(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,client_id BIGINT NOT NULL REFERENCES clients(id),plate VARCHAR(12) UNIQUE NOT NULL,brand VARCHAR(60) NOT NULL,model VARCHAR(60) NOT NULL,vehicle_year INT,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)",
      "CREATE TABLE IF NOT EXISTS parts(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,code VARCHAR(40) UNIQUE NOT NULL,name VARCHAR(120) NOT NULL,category VARCHAR(80) NOT NULL,supplier VARCHAR(120) NOT NULL,stock_total INT NOT NULL CHECK(stock_total>=0),stock_available INT NOT NULL CHECK(stock_available>=0),unit_price DECIMAL(14,2) NOT NULL CHECK(unit_price>=0),active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)",
      "CREATE TABLE IF NOT EXISTS users(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,username VARCHAR(60) UNIQUE NOT NULL,password VARCHAR(120) NOT NULL,full_name VARCHAR(120) NOT NULL,role VARCHAR(20) NOT NULL,status VARCHAR(20) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)",
      "CREATE TABLE IF NOT EXISTS service_orders(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,client_id BIGINT NOT NULL REFERENCES clients(id),vehicle_id BIGINT NOT NULL REFERENCES vehicles(id),mechanic VARCHAR(120) NOT NULL,entry_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,problem VARCHAR(500) NOT NULL,diagnosis VARCHAR(500),status VARCHAR(30) NOT NULL,final_cost DECIMAL(14,2))",
      "CREATE TABLE IF NOT EXISTS order_parts(order_id BIGINT NOT NULL REFERENCES service_orders(id),part_id BIGINT NOT NULL REFERENCES parts(id),quantity INT NOT NULL CHECK(quantity>0),unit_price DECIMAL(14,2) NOT NULL,PRIMARY KEY(order_id,part_id))"
    };
    try (Connection c = getConnection();
        Statement st = c.createStatement()) {
      for (String sql : ddl) st.execute(sql);
    }

    String adminSql =
        "INSERT INTO users(username,password,full_name,role,status) "
            + "VALUES(?,?,'Administrador','ADMIN','ACTIVO') "
            + "ON CONFLICT (username) DO UPDATE SET password=EXCLUDED.password";

    try (Connection connection = getConnection();
        PreparedStatement statement = connection.prepareStatement(adminSql)) {
      statement.setString(1, ADMIN_USERNAME);
      statement.setString(2, ADMIN_PASSWORD);
      statement.executeUpdate();
    }
  }

}
